spring:
    datasource:
      url: jdbc:h2:mem:demo
      driverClassName: org.h2.Driver
      username: admin
      password: admin
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect


